version: "3.9"
services:
  service:
    build: .
    environment:
      - POSTGRES_URL=psql://postgres:5432
      - IO_BACKEND_BASE_URL=https://app-backend.io.italia.it
    ports:
      - "3000:3000"
  postgres:
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: db
