version: "3.9"
services:
  service:
    build: .
    environment:
      - PORT=3001
      - MONGODB_URL=mongodb://root:randompassword@mongodb:27017/testdb?authSource=admin
      - IO_BACKEND_BASE_URL=https://app-backend.io.italia.it
    ports:
      - "3001:3001"
  mongodb:
    # This image automatically creates a replica set required for transactions
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: randompassword
      MONGO_INITDB_DATABASE: test
    ports:
      - 27017:27017