version: "3.9"
services:
  service:
    build: .
    environment:
      - PORT=3001
      - POSTGRES_URL=postgresql://user:randompassword@postgres:5432/db
      - IO_BACKEND_BASE_URL=https://app-backend.io.italia.it
    ports:
      - "3001:3001"
  postgres:
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: db
